# ---------------------------
# Hexo Theme Solitude
# Author: Ever Fu
# Github: https://github.com/everfu/hexo-theme-solitude
#
# Guide: https://solitude.js.org
# You can get more detailed help from the guide
# æŒ‡å—ï¼šhttps://solitude.js.org
# ä½ å¯ä»¥ä»æŒ‡å—ä¸­è·å–æ›´è¯¦ç»†çš„å¸®åŠ©
#
# sponsor: https://ko-fi.com/everfu
# èµåŠ©ï¼šhttps://afdian.com/a/everfu
# ---------------------------

### Basic configuration

# --------------------------- ç½‘ç«™ä¿¡æ¯ start ---------------------------
site:
  name:
    class: text
    custom: å®å“¥åšå®¢
  icon: https://pan.811520.xyz/2024-10/1728197294016.webp
# --------------------------- ç½‘ç«™ä¿¡æ¯ end ---------------------------

# --------------------------- å¯¼èˆªæ  start ---------------------------

  menu:
    æ–°é—»:
      æ¯æ—¥æ—©æŠ¥: https://readhub.cn/daily || https://unavatar.io/readhub.cn
      æ–°é—»æ±‡èš: https://xw.653827.xyz/ || https://s3.bmp.ovh/imgs/2025/04/06/e8efeb29eff52acb.png
      æ¯æ—¥ç®€æŠ¥: https://kui.li/news || https://unavatar.io/kui.li
      æ‡’äººæ—©æŠ¥: https://lazybook.netlify.app/#/blog/morning?id=%e6%96%b0%e9%97%bb%e6%97%a9%e6%8a%a5 || https://unavatar.io/lazybook.netlify.app
      é€Ÿçƒ­ç‚¹: https://www.suredian.com/ || https://unavatar.io/www.suredian.com
      Feedly: https://feedly.com/i/my/me || https://unavatar.io/feedly.com
      FOLO: https://app.follow.is/timeline/view-0/all/pending || https://unavatar.io/app.follow.is
      è´¢ç»æ–°é—»: https://sina-news.vercel.app/ || https://s3.bmp.ovh/imgs/2025/04/16/73d944905f090a66.jpg

    å¤©æ°”:
      æ³°å®‰å¤©æ°”: https://www.qweather.com/weather/tai'an-101120801.html || https://s3.bmp.ovh/imgs/2025/04/11/cbbf91bbd2b4df69.png
      å²±å²³å¤©æ°”: https://tianqi.moji.com/weather/china/shandong/daiyue-district || https://s3.bmp.ovh/imgs/2025/04/16/b54015cf0979f19a.png
      æ³°å®‰å¤©æ°”2: https://tianqi.qq.com/index.htm || https://unavatar.io/tianqi.qq.com
      å¤©æ°”å›: https://waptianqi.tianqijun.com/weather1d/101120801/ || https://s3.bmp.ovh/imgs/2025/04/16/1e7a5f1f40584cde.png
      æ³°å®‰å¤©æ°”å¡ç‰‡: https://file.baoge.wang/%E6%96%87%E4%BB%B6%E5%A4%B9/%E6%B3%B0%E5%AE%89%E5%B8%82%E5%A4%A9%E6%B0%94 || https://s3.bmp.ovh/imgs/2025/07/22/be89ef3aa00a9528.png

    å½±é™¢:
      LibreTV-ys: https://ys.baoge.wang/ || https://s3.bmp.ovh/imgs/2025/04/17/d51d8f514bf4ea90.png
      LibreTV: https://libretv.baoge.wang/ || https://s3.bmp.ovh/imgs/2025/04/17/d51d8f514bf4ea90.png
      LibreTV-x: https://libretv-x.baoge.wang/ || https://s3.bmp.ovh/imgs/2025/04/17/d51d8f514bf4ea90.png
      MoonTV: https://nnypxrykegia.ap-northeast-1.clawcloudrun.com/ || https://nnypxrykegia.ap-northeast-1.clawcloudrun.com/favicon.ico
      å½±è§†: https://vd.ruo.my/ || https://s3.bmp.ovh/imgs/2025/04/19/fa9b145465c4e90e.png
      è€ç‹ç”µå½±: https://laowang.co/ || https://wp-cdn.4ce.cn/v2/D3rQsvy.jpeg

    å¯¼èˆª:
      å½©è™¹å·¥å…·ç½‘: https://tool.cccyun.cc/ || https://s3.bmp.ovh/imgs/2025/03/16/2499eb4888a8aa1a.png
      ç½‘å€å¯¼èˆª: https://navpage.pagex.top/ || https://unavatar.io/navpage.pagex.top
      ä¹¦ç­¾å¯¼èˆª: https://dh.baoge.wang/ || https://s3.bmp.ovh/imgs/2025/07/06/4eefad659ac22401.webp
      å¯¼èˆªå‘å¸ƒé¡µ: https://wang.baoge.wang/ || https://s3.bmp.ovh/imgs/2025/07/23/dae93b237adc3a0d.png

    AI:
      AIå¯¼èˆª: https://www.aidh.cn/ || https://s3.bmp.ovh/imgs/2025/04/16/1e7a5f1f40584cde.png
      AIå·¥å…·ç®±: https://aiproducthome.top/ || https://s3.bmp.ovh/imgs/2025/04/16/bf5e7295d50e3148.png
      AIä»“åº“: https://ai-cangku.com/ || https://unavatar.io/ai-cangku.com
      LMarena: https://lmarena.ai/ || https://unavatar.io/lmarena.ai

    
  right:
    random: false
    custom: []
# --------------------------- å¯¼èˆªæ  end ---------------------------

# --------------------------- é¦–é¡µé¡¶éƒ¨ start ---------------------------
hometop:
  enable: true
  banner:
    title: å®é™è‡´è¿œ <br> çƒ­çˆ±ç”Ÿæ´»
    url: Hexo Theme Solitude
    icon:
      HTML:
        img: https://i.postimg.cc/vBWVnY8q/html.png
        color: "#e9572b"
      JS:
        img: https://i.postimg.cc/3N10Ltv2/js.png
        color: "#f7cb4f"
      Docker:
        img: https://i.postimg.cc/8Pk6Fg24/docker.png
        color: "#57b6e6"
      Flutter:
        img: https://i.postimg.cc/hPC7T3gB/flutter.png
        color: "#ffffff"
      WebPack:
        img: https://i.postimg.cc/dVLZBmtT/webpack.png
        color: "#2e3a41"
      Git:
        img: https://i.postimg.cc/nhgjwjCS/git.png
        color: "#df5b40"
  group:
    çƒ­é—¨: /tags/Fire/ || fas fa-fire || linear-gradient(to right,#f65,#ffbf37)
  recommendList:
    sup: ç½®é¡¶
    title: Solitude å®˜æ–¹æ–‡æ¡£
    url: https://solitude.js.org/
    img: https://pan.811520.xyz/2024-10/1728279557702.webp
    color: "none"
carousel: false
# --------------------------- é¦–é¡µé¡¶éƒ¨ end ---------------------------

# --------------------------- ä¾§è¾¹æ  start ---------------------------
aside:
  home:
    noSticky: "about"
    Sticky: "allInfo"
  post:
    noSticky: "about"
    Sticky: "newestPost"
  page:
    noSticky: "about"
    Sticky: "newestPost,allInfo"
  position: 1
  card:
    style: 0
    author:
      img: https://pan.811520.xyz/2024-10/1728197294016.webp
      sticker:
    url: /about/
    background:
    content: è¿™æ˜¯æˆ‘çš„åšå®¢
    content2: ä¸€ä¸ªçƒ­çˆ±ç”Ÿæ´»çš„äºº
    sayhello:
      morning: âœ¨ æ—©ä¸Šå¥½ï¼Œåˆæ˜¯æ–°çš„ä¸€å¤©
      noon: åˆä¼‘æ—¶é—´åˆ°äº†
      afternoon: ä¸‹åˆèŒ¶ ğŸµ
      night: æ—©ç‚¹ç¡è§‰
      goodnight: æ™šå®‰ ğŸ˜´
    sayhello2:
    information:
      Github: https://github.com/everfu || fab fa-github
      Bilibili: https://space.bilibili.com/1329819902 || fab fa-bilibili
      å¾®ä¿¡: https://your-wechat-link || fab fa-weixin
      é‚®ç®±: mailto:your@email.com || fas fa-envelope
  flip:
    favicon:
    face:
    backface:
    backcolor: "var(--efu-blue)"
  toc:
    post: true
    page: false
    vague: true
  tags:
    enable: true
    limit: 20
    highlight_list:
  archive:
    enable: true
    type: "month"
  siteinfo:
    postcount: true
    wordcount: false
    pv: true
    uv: true
    updatetime: true
    runtimeenable: true
    runtime: "2025-07-20 00:00:00"
# --------------------------- ä¾§è¾¹æ  end ---------------------------

# --------------------------- é¡µé¢é»˜è®¤è®¾ç½® start ---------------------------
page:
  error: true
  tags: true
  categories: true
  archives: 0
  default:
    cover:
# --------------------------- é¡µé¢é»˜è®¤è®¾ç½® end ---------------------------

# --------------------------- æ–‡ç« é»˜è®¤è®¾ç½® start ---------------------------
post:
  default:
    top_cover: true
    cover:
    locate: China,hubei
    copyright:
      enable: true
      author:
        url: /about/
        img:
      license: CC BY-NC-SA 4.0
      licenurl: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
  meta:
    date: true
    updated: true
    locate: false
    wordcount: true
    readtime: true
    pv: true
    comment: true
  award:
    enable: false
    appreciators: /about/
    title:
    desc:
    list:
  share:
    enable: true
    list:
      - qq
      - weibo
      - twitter
      - facebook
      - telegram
      - link
      - qrcode
  rss: /atom.xml
  covercolor:
    enable: false
    mode: local
    api: https://api.qjqq.cn/api/Imgcolor?img=
    time: 43200000
  footer:
    enable: false
    desc:
    button:
      enable: true
      name:
      url: /about/
# --------------------------- æ–‡ç« é»˜è®¤è®¾ç½® end ---------------------------

# --------------------------- ä¸»é¢˜é¢œè‰² start ---------------------------
theme_color:
  dark: "#ffc848"
  light: "#425AEF"
# --------------------------- ä¸»é¢˜é¢œè‰² end ---------------------------

# --------------------------- æ˜¾ç¤ºæ¨¡å¼ start ---------------------------
display_mode:
  type: auto
  universe: false
# --------------------------- æ˜¾ç¤ºæ¨¡å¼ end ---------------------------

# --------------------------- å­—ä½“ start ---------------------------
font:
  font-size: 16px
  code-font-size: 16px
  font-family: "PingFang SC, Hiragino Sans GB, Microsoft YaHei"
  code-font-family: '"monospace", monospace'
# --------------------------- å­—ä½“ end ---------------------------

# --------------------------- èƒŒæ™¯å›¾ç‰‡ start ---------------------------
background:
  enable: false
  opacity: .2
  dark: https://i.pinimg.com/originals/d8/b3/9d/d8b39d12b653810db452c437211aeb2e.png
  light: https://i.pinimg.com/originals/93/57/38/935738ed9657b296c2ef0ebd2151eb66.jpg
# --------------------------- èƒŒæ™¯å›¾ç‰‡ end ---------------------------

# --------------------------- é¡µè„š start ---------------------------
footer:
  information:
    author: https://pan.811520.xyz/2024-10/1728197294016.webp
    
  group:
  randomlink: false
  license:
  links:
    - name: Theme
      url: https://github.com/everfu/hexo-theme-solitude
    - name: RSS
      url: /atom.xml
# --------------------------- é¡µè„š end ---------------------------

# å…¶ä½™é…ç½®é¡¹ï¼ˆå¦‚ commentã€searchã€musicã€capsuleã€highlightã€katexã€pwaã€CDNç­‰ï¼‰å¯å‚è€ƒå®˜æ–¹æ–‡æ¡£æˆ–ä½ åŸæœ‰çš„é…ç½®ç»§ç»­è¡¥å……
