# ---------------------------
# Hexo Theme Solitude
# Author: Ever Fu
# Github: https://github.com/everfu/hexo-theme-solitude
#
# Guide: https://solitude.js.org
# ä½ å¯ä»¥ä»æŒ‡å—ä¸­è·å–æ›´è¯¦ç»†çš„å¸®åŠ©
# ---------------------------

### Basic configuration

# --------------------------- ç½‘ç«™ä¿¡æ¯ start ---------------------------
site:
  name:
    class: text # text / i_class / img
    custom: Solitude # Solitude / fas fa-ghost / /img/pwa/favicon.ico
  icon: https://pan.811520.xyz/2024-10/1728197294016.webp
# --------------------------- ç½‘ç«™ä¿¡æ¯ end ---------------------------

# --------------------------- å¯¼èˆªæ  start ---------------------------
nav:
  # å·¦ä¾§LOGOæˆ–æ ‡é¢˜ç»„ï¼Œå¯è‡ªå®šä¹‰æ·»åŠ 
  group:
    # - name: é¡¹ç›®
    #   url: /project/
    #   icon: fas fa-code

  # é¡¶éƒ¨èœå•ï¼ˆå¯è‡ªç”±å¢åˆ ï¼Œæ”¯æŒå¤šçº§èœå•ï¼‰
  menu:
  æ–°é—»:
    æ¯æ—¥æ—©æŠ¥: https://readhub.cn/daily || https://unavatar.io/readhub.cn
    æ–°é—»æ±‡èš: https://xw.653827.xyz/ || https://s3.bmp.ovh/imgs/2025/04/06/e8efeb29eff52acb.png
    æ¯æ—¥ç®€æŠ¥: https://kui.li/news || https://unavatar.io/kui.li
    æ‡’äººæ—©æŠ¥: https://lazybook.netlify.app/#/blog/morning?id=%e6%96%b0%e9%97%bb%e6%97%a9%e6%8a%a5 || https://unavatar.io/lazybook.netlify.app
    é€Ÿçƒ­ç‚¹: https://www.suredian.com/ || https://unavatar.io/www.suredian.com
    Feedly: https://feedly.com/i/my/me || https://unavatar.io/feedly.com
    FOLO: https://app.follow.is/timeline/view-0/all/pending || https://unavatar.io/app.follow.is
    è´¢ç»æ–°é—»: https://sina-news.vercel.app/ || https://s3.bmp.ovh/imgs/2025/04/16/73d944905f090a66.jpg

  å¤©æ°”:
    æ³°å®‰å¤©æ°”: https://www.qweather.com/weather/tai'an-101120801.html || https://s3.bmp.ovh/imgs/2025/04/11/cbbf91bbd2b4df69.png
    å²±å²³å¤©æ°”: https://tianqi.moji.com/weather/china/shandong/daiyue-district || https://s3.bmp.ovh/imgs/2025/04/16/b54015cf0979f19a.png
    æ³°å®‰å¤©æ°”2: https://tianqi.qq.com/index.htm || https://unavatar.io/tianqi.qq.com
    å¤©æ°”å›: https://waptianqi.tianqijun.com/weather1d/101120801/ || https://s3.bmp.ovh/imgs/2025/04/16/1e7a5f1f40584cde.png
    æ³°å®‰å¤©æ°”å¡ç‰‡: https://file.baoge.wang/%E6%96%87%E4%BB%B6%E5%A4%B9/%E6%B3%B0%E5%AE%89%E5%B8%82%E5%A4%A9%E6%B0%94 || https://s3.bmp.ovh/imgs/2025/07/22/be89ef3aa00a9528.png

  å½±é™¢:
    LibreTV-ys: https://ys.baoge.wang/ || https://s3.bmp.ovh/imgs/2025/04/17/d51d8f514bf4ea90.png
    LibreTV: https://libretv.baoge.wang/ || https://s3.bmp.ovh/imgs/2025/04/17/d51d8f514bf4ea90.png
    LibreTV-x: https://libretv-x.baoge.wang/ || https://s3.bmp.ovh/imgs/2025/04/17/d51d8f514bf4ea90.png
    MoonTV: https://nnypxrykegia.ap-northeast-1.clawcloudrun.com/ || https://nnypxrykegia.ap-northeast-1.clawcloudrun.com/favicon.ico
    å½±è§†: https://vd.ruo.my/ || https://s3.bmp.ovh/imgs/2025/04/19/fa9b145465c4e90e.png
    è€ç‹ç”µå½±: https://laowang.co/ || https://wp-cdn.4ce.cn/v2/D3rQsvy.jpeg

  å¯¼èˆª:
    å½©è™¹å·¥å…·ç½‘: https://tool.cccyun.cc/ || https://s3.bmp.ovh/imgs/2025/03/16/2499eb4888a8aa1a.png
    ç½‘å€å¯¼èˆª: https://navpage.pagex.top/ || https://unavatar.io/navpage.pagex.top
    ä¹¦ç­¾å¯¼èˆª: https://dh.baoge.wang/ || https://s3.bmp.ovh/imgs/2025/07/06/4eefad659ac22401.webp
    å¯¼èˆªå‘å¸ƒé¡µ: https://wang.baoge.wang/ || https://s3.bmp.ovh/imgs/2025/07/23/dae93b237adc3a0d.png

  AI:
    AIå¯¼èˆª: https://www.aidh.cn/ || https://s3.bmp.ovh/imgs/2025/04/16/1e7a5f1f40584cde.png
    AIå·¥å…·ç®±: https://aiproducthome.top/ || https://s3.bmp.ovh/imgs/2025/04/16/bf5e7295d50e3148.png
    AIä»“åº“: https://ai-cangku.com/ || https://unavatar.io/ai-cangku.com
    LMarena: https://lmarena.ai/ || https://unavatar.io/lmarena.ai

  

  # å³ä¾§æŒ‰é’®ï¼ˆå¯è‡ªå®šä¹‰å¤šä¸ªæŒ‰é’®ï¼‰
  right:
    random: false
    custom:
      - name: Start
        url: https://www.travellings.cn/go.html
        icon: fas fa-train
        onclick:
        id: travellings_button
# --------------------------- å¯¼èˆªæ  end ---------------------------

# --------------------------- é¦–é¡µé¡¶éƒ¨ start ---------------------------
hometop:
  enable: true
  banner:
    title: å®é™è‡´è¿œ <br> çƒ­çˆ±ç”Ÿæ´»
    url: Hexo Theme Solitude
    icon:
      HTML:
        img: https://i.postimg.cc/vBWVnY8q/html.png
        color: "#e9572b"
      JS:
        img: https://i.postimg.cc/3N10Ltv2/js.png
        color: "#f7cb4f"
      Docker:
        img: https://i.postimg.cc/8Pk6Fg24/docker.png
        color: "#57b6e6"
      Flutter:
        img: https://i.postimg.cc/hPC7T3gB/flutter.png
        color: "#ffffff"
      WebPack:
        img: https://i.postimg.cc/dVLZBmtT/webpack.png
        color: "#2e3a41"
      Git:
        img: https://i.postimg.cc/nhgjwjCS/git.png
        color: "#df5b40"
  group:
    çƒ­é—¨: /tags/Fire/ || fas fa-fire || linear-gradient(to right,#f65,#ffbf37)
  recommendList:
    sup: ç½®é¡¶
    title: Solitude å®˜æ–¹æ–‡æ¡£
    url: https://solitude.js.org/
    img: https://pan.811520.xyz/2024-10/1728279557702.webp
    color: "none"
carousel: false
# --------------------------- é¦–é¡µé¡¶éƒ¨ end ---------------------------

# --------------------------- ä¾§è¾¹æ  start ---------------------------
aside:
  # ä¾§è¾¹æ ä½ç½®(0: å·¦ 1: å³)
  position: 0 # Sidebar positioning(0: left 1: right)
  home:
    noSticky: "about"
    Sticky: "allInfo"
  post:
    noSticky: "about"
    Sticky: "newestPost"
  page:
    noSticky: "about"
    Sticky: "newestPost,allInfo"
  card:
    style: 0
    author:
      img: https://pan.811520.xyz/2024-10/1728197294016.webp
      sticker:
    url: /about/
    background:
    content: è¿™æ˜¯æˆ‘çš„åšå®¢
    content2: ä¸€ä¸ªçƒ­çˆ±ç”Ÿæ´»çš„äºº
    sayhello:
      morning: âœ¨ æ—©ä¸Šå¥½ï¼Œåˆæ˜¯æ–°çš„ä¸€å¤©
      noon: åˆä¼‘æ—¶é—´åˆ°äº†
      afternoon: ä¸‹åˆèŒ¶ ğŸµ
      night: æ—©ç‚¹ç¡è§‰
      goodnight: æ™šå®‰ ğŸ˜´
    sayhello2:
    information:
      Github: https://github.com/everfu || fab fa-github
      Bilibili: https://space.bilibili.com/1329819902 || fab fa-bilibili
      å¾®ä¿¡: https://your-wechat-link || fab fa-weixin
      é‚®ç®±: mailto:your@email.com || fas fa-envelope
  flip:
    favicon:
    face:
    backface:
    backcolor: "var(--efu-blue)"
  toc:
    post: true
    page: false
    vague: true
  tags:
    enable: true
    limit: 20
    highlight_list:
  archive:
    enable: true
    type: "month"
  siteinfo:
    postcount: true
    wordcount: false
    pv: true
    uv: true
    updatetime: true
    runtimeenable: true
    runtime: "2025-07-20 00:00:00"
# --------------------------- ä¾§è¾¹æ  end ---------------------------

# --------------------------- é¦–é¡µé¡¶éƒ¨ end ---------------------------

# --------------------------- é¡µé¢é»˜è®¤è®¾ç½® start ---------------------------
page:
  error: true
  tags: true
  categories: true
  archives: 0
  default:
    cover:
# --------------------------- é¡µé¢é»˜è®¤è®¾ç½® end ---------------------------

# --------------------------- æ–‡ç« é»˜è®¤è®¾ç½® start ---------------------------
post:
  default:
    top_cover: true
    cover:
    locate: China,hubei
    copyright:
      enable: true
      author:
        url: /about/
        img:
      license: CC BY-NC-SA 4.0
      licenurl: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
  meta:
    date: true
    updated: true
    locate: false
    wordcount: true
    readtime: true
    pv: true
    comment: true
  award:
    enable: false
    appreciators: /about/
    title:
    desc:
    list:
  share:
    enable: true
    list:
      - qq
      - weibo
      - twitter
      - facebook
      - telegram
      - link
      - qrcode
  rss: /atom.xml
  covercolor:
    enable: false
    mode: local
    api: https://api.qjqq.cn/api/Imgcolor?img=
    time: 43200000
  footer:
    enable: false
    desc:
    button:
      enable: true
      name:
      url: /about/
# --------------------------- æ–‡ç« é»˜è®¤è®¾ç½® end ---------------------------

# --------------------------- ä¸»é¢˜é¢œè‰² start ---------------------------
theme_color:
  dark: "#ffc848"
  light: "#425AEF"
# --------------------------- ä¸»é¢˜é¢œè‰² end ---------------------------

# --------------------------- æ˜¾ç¤ºæ¨¡å¼ start ---------------------------
display_mode:
  type: auto
  universe: false
# --------------------------- æ˜¾ç¤ºæ¨¡å¼ end ---------------------------

# --------------------------- å­—ä½“ start ---------------------------
font:
  font-size: 16px
  code-font-size: 16px
  font-family: "PingFang SC, Hiragino Sans GB, Microsoft YaHei"
  code-font-family: '"monospace", monospace'
# --------------------------- å­—ä½“ end ---------------------------

# --------------------------- èƒŒæ™¯å›¾ç‰‡ start ---------------------------
background:
  enable: false
  opacity: .2
  dark: https://i.pinimg.com/originals/d8/b3/9d/d8b39d12b653810db452c437211aeb2e.png
  light: https://i.pinimg.com/originals/93/57/38/935738ed9657b296c2ef0ebd2151eb66.jpg
# --------------------------- èƒŒæ™¯å›¾ç‰‡ end ---------------------------

# --------------------------- start ---------------------------
lure:
  enable: false
  jump: 404 Not Found
  back: ãƒ¾(â‰§âˆ‡â‰¦*)ã‚å“ˆå“ˆï¼Œä½ ä¸Šå½“äº†ï¼
# --------------------------- end ---------------------------

# --------------------------- æ–‡ç« è¿‡æœŸæé†’ start ---------------------------
expire:
  enable: false
  time: 180
  position: top
  text_prev: "This article expired "
  text_next: " day ago, if the content does not match, please contact the webmaster to update it."
# --------------------------- æ–‡ç« è¿‡æœŸæé†’ end ---------------------------

# --------------------------- é¦–é¡µæ–‡ç« æ˜¾ç¤ºæ–¹å¼ start ---------------------------
index_post_list:
  direction: column
  column: 2
  cover: both
# --------------------------- é¦–é¡µæ–‡ç« æ˜¾ç¤ºæ–¹å¼ end ---------------------------

# --------------------------- æ˜¾ç¤ºç›¸å…³æ–‡ç«  start ---------------------------
related_post:
  enable: true
  limit: 4
  date_type: created
# --------------------------- æ˜¾ç¤ºç›¸å…³æ–‡ç«  end ---------------------------

# --------------------------- å³é”®èœå• start ---------------------------
right_menu:
  enable: false
  commentBarrage: false
  ctrlOriginalMenu: false
  translate: false
  custom_list:
# --------------------------- å³é”®èœå• end -----------------------

# --------------------------- å¤åˆ¶ä¿¡æ¯ start ---------------------------
copy:
  enable: false
  copyright:
    enable: false
    limit: 50
# --------------------------- å¤åˆ¶ä¿¡æ¯ end ---------------------------

# --------------------------- start ---------------------------
mermaid: false
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
chart: false
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
typeit: false
# --------------------------- end ---------------------------

### Extended configuration

# --------------------------- æ§åˆ¶å° start ---------------------------
console:
  enable: true
  recentComment:
    enable: true
    storage: .5
  card:
    tags: true
    archive: true
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
translate:
  enable: true
  defaultEncoding: 2
  translateDelay: 0
# --------------------------- end ---------------------------

# --------------------------- å³ä¸‹è§’æ‚¬åœå¯¼èˆªæ  start ---------------------------
rightside:
  enable: false
  percent: false
  hide:
    enable: false
    translate: false
    mode: false
    aside: false
# --------------------------- å³ä¸‹è§’æ‚¬åœå¯¼èˆªæ  start ---------------------------

# --------------------------- é¡µè„š start ---------------------------
footer:
  information:
    author: https://pan.811520.xyz/2024-10/1728197294016.webp
    
  group:
  randomlink: false
  license:
  links:
    - name: Theme
      url: https://github.com/everfu/hexo-theme-solitude
    - name: RSS
      url: /atom.xml
# --------------------------- é¡µè„š end ---------------------------

# --------------------------- 404 é¡µé¢ start ---------------------------
errorpage:
  img: /img/404.avif
  text: =awa= Page Not Found
  recommendList: true
# --------------------------- 404 é¡µé¢ end ---------------------------

# --------------------------- éŸ³ä¹API start ---------------------------
meting_api: "https://meting.everfu.cn/?server=:server&type=:type&id=:id&auth=:auth&r=:r"
# --------------------------- éŸ³ä¹API end ---------------------------

# --------------------------- éŸ³ä¹é¦† start ---------------------------
music:
  enable: true
  id: 1994908354
  server: netease
  type: playlist
  volume: 0.8
  mutex: true
# --------------------------- éŸ³ä¹é¦† end ---------------------------

# --------------------------- éŸ³ä¹èƒ¶å›Š start ---------------------------
capsule:
  enable: false
  id: 8407304077
  server: netease
  type: playlist
# --------------------------- éŸ³ä¹èƒ¶å›Š end ---------------------------

# --------------------------- å¿«æ·èœå• start ---------------------------
keyboard:
  enable: false
  list:
# --------------------------- å¿«æ·èœå• end ---------------------------

# --------------------------- å›¾ç‰‡æ‡’åŠ è½½ start ---------------------------
lazyload:
  enable: false
  field: site
  placeholder: /img/loading.avif
  errorimg: /img/error_load.avif
# --------------------------- å›¾ç‰‡æ‡’åŠ è½½ end ---------------------------

# --------------------------- ä¸»é¡µåŠ è½½ start ---------------------------
loading:
  fullpage: false
  pace: true
# --------------------------- ä¸»é¡µåŠ è½½ end ---------------------------

# --------------------------- ä»£ç å—é«˜äº® start ---------------------------
highlight:
  enable: true
  limit: 200
  copy: true
  expand: true
  theme: default
  color: default
# --------------------------- ä»£ç å—é«˜äº® end ---------------------------

# --------------------------- å›¾ç‰‡ç¯ç®± start ---------------------------
lightbox: false
fancybox: true
mediumZoom: false
# --------------------------- å›¾ç‰‡ç¯ç®± end ---------------------------

# --------------------------- çºªå¿µæ—¥å˜ç° start ---------------------------
memorial:
  enable: false
  date:
# --------------------------- çºªå¿µæ—¥å˜ç° end ---------------------------

# --------------------------- start ---------------------------
OpenGraph:
  enable: false
  options:
# --------------------------- end ---------------------------

# --------------------------- å­—æ•°ç»Ÿè®¡ start ---------------------------
wordcount: false
# --------------------------- å­—æ•°ç»Ÿè®¡ end ---------------------------

# --------------------------- æ•°å­¦å…¬å¼ start ---------------------------
katex:
  enable: true
  per_page: false
  copytex: true
# --------------------------- æ•°å­¦å…¬å¼ end ---------------------------

# --------------------------- start ---------------------------
verify_site:
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
css_prefix: false
# --------------------------- end ---------------------------

# --------------------------- æ‰©å±•è®¾ç½® start ---------------------------
extends:
  head:
  body:
# --------------------------- æ‰©å±•è®¾ç½®  end ---------------------------

# --------------------------- start ---------------------------
pwa:
  enable: false
  manifest: /manifest.json
  theme_color: "#006a73"
  mask_icon: /img/pwa/favicon.png
  apple_touch_icon: /img/pwa/favicon.png
  bookmark_icon: /img/pwa/favicon.png
  favicon_32_32: /img/pwa/favicon_32.png
  favicon_16_16: /img/pwa/favicon_16.png
# --------------------------- end ---------------------------

# --------------------------- è¯„è®ºç³»ç»Ÿ start ---------------------------
comment:
  use:
  commentBarrage: true
  lazyload: false
  count: true
  pv: true
  avatar: https://gravatar.com/avatar
  hot_tip:
    enable: false
    count: 3
  newest_comment:
    enable: true
    storage: .5
    limit: 5
twikoo:
  envId:
  region:
  style: true
  accessToken:
  option:
waline:
  envId:
  pageview: false
  option:
valine:
  appId:
  appKey:
  serverURLs:
  avatar:
  visitor: false
  style: true
  option:
artalk:
  server:
  site:
  option:
giscus:
  repo:
  repo_id:
  category_id:
  theme:
    light: light
    dark: dark
  option:
# --------------------------- è¯„è®ºç³»ç»Ÿ end ---------------------------

# --------------------------- æœç´¢ç³»ç»Ÿ start ---------------------------
search:
  enable: true
  type: local
  tags:
  algolia:
    appId: "Z7A3XW4R2I"
    apiKey: "12db1ad54372045549ef465881c17e743"
    adminApiKey: "40321c7c207e7f73b63a19aa24c4761b"
    chunkSize: 5000
    indexName: ""
    fields:
  local:
    preload: false
    CDN:
# --------------------------- æœç´¢ç³»ç»Ÿ end ---------------------------

# --------------------------- å¼¹å¹•ç•™è¨€ start ---------------------------
envelope:
  enable: false
  line: 10
  speed: 20
  hover: true
  loop: true
  page: /message/
# --------------------------- å¼¹å¹•ç•™è¨€ end ---------------------------

# --------------------------- å³åˆ»çŸ­æ–‡ start ---------------------------
says:
  enable: true
  home_mini: false
  page: /essay/
  style: 1
  strip: 30
# --------------------------- å³åˆ»çŸ­æ–‡ end ---------------------------

# --------------------------- æœ€è¿‘è¯„è®º start ---------------------------
recent_comments:
  enable: true
  limit: 50
  cache: 0.2
  page: /recentcomments/
  img: /img/recent_c.avif
# --------------------------- æœ€è¿‘è¯„è®º end ---------------------------

# --------------------------- busuanzi start ---------------------------
busuanzi: false
busuanzi_use: 0
# --------------------------- busuanzi end ---------------------------

# --------------------------- AI start ---------------------------
tianli_talk:
  enable: false
  title: æ™ºèƒ½å®¢æœä¸æœç´¢
  key:
  option:
post_ai:
  enable: false
  modelName: GPT 4
  key:
  talk:
  randomPost: false
  report: https://solitude.js.org
  tips:
# --------------------------- AI end ---------------------------

# --------------------------- è°·æ­Œå¹¿å‘Š start ---------------------------
google_adsense:
  enable: false
  auto_ads: false
  enable_page_level_ads: true
  aside_card: true
  post_card: true
  post_content: true
  js: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
  client:
  slot:
# --------------------------- è°·æ­Œå¹¿å‘Š end ---------------------------

# --------------------------- CDNè®¾ç½® start ---------------------------
CDN:
  internal: local
  third_party: cdnjs
  version: true
  custom_format: //open.lightxi.com/cdnjs/ajax/libs/${cdnjs_name}/${version}/${min_cdnjs_file}
  options:
# --------------------------- CDNè®¾ç½® end ---------------------------
